satyawikananda/awesome-music-playlist

README.md

Added : 
- R&B Genre
- POP Genre

Add Genres and Playlists

---

README.md

Considering fix this contribution guide table and add subgenres?

Fix contribution guide table and add subgenres

---

README.md

add playlist

---

README.md

add this superbeaver album song

add playlist J-Pop

---

README.md

Add new podcast and playlist, also mentioned my profile as contributor

chores(readme): add new podcast and playlist

---

.all-contributorsrc
README.md

ive add new song in this playlist ,need for review perhaps ?

add new playlist

---

README.md

Add 1 Pop Playlist to README.md. Mention me as a Contributor.

Add new Pop Playlist

---

README.md

add tilawah playlist

---

README.md

- **Metal**: Dream Theater
- **Kawaii-metal**: BABYMETAL Favorite
- **EDM**: KODOMOi
- **Lo-Fi**: Kupla
- **Instrumental**: TSFH

Add playlist: Metal, Kawaii-metal, EDM, Lo-Fi, Instrumental.

---

.all-contributorsrc
README.md

Add playlist Acoustic from Youtube Music

add playlist acoustic

---

README.md

README: Link playlist as hyperlink

---

README.md

add my Favorite Rap Genre Playlist to this project

add new playlist and new genre

---

README.md

Ada kesalahan penulisan di tabel lofi hiphop playlist nomor 2, seharusnya spotify, bukan youtube

correct typo from lofi hiphop playlist

---

README.md

Aku sblmnya salah malah ngasih track wkwk, silahkan di cek lg broo @satyawikananda

remove a track and change it into playlist at EDM section

---

README.md

Add new playlist and genre k-pop

---

README.md

Halo, saya ingin menambahkan dua podcast dengan kategori pop kultur, yaitu LUTALK dan Variant: The Podcast. Mohon reviewnya 🙏😁

Menambahkan Dua Podcast dengan Kategori Pop Kultur

---

README.md

add my favourite lofi playlist

add lofi playlist in README.md

---

.all-contributorsrc
README.md

add my favorit songs at J-Pop

---

README.md

saya sudah menambahkan playlist musik kesukaan saya.

add my favorite playlist song

---

README.md

Added New JPOP playlist

---

README.md

Halo saya frits sasia, saya mencoba untuk berkontribusi dengan cara menambahkan playlist ke repositori ini
terima kasih :)

add new playlist, by fritssasia

---

README.md

add my favorite playlist from lol club

update pop playlist

---

README.md

Adding new playlist on instrumental section in README.md

adding playlist (Sythwave & retrowave)

---

README.md

saya menambahkan playlist on ok rock dari youtube playlist

add 1 playlist in rock genre

---

docs/contribution.md

I think, the order sequence of steps for creating pull request should be
3. Create your feature branch: `git checkout -b your-new-branch`
4. Edit that what you want to change

docs: edit the sequence of steps for creating pull request

---

.all-contributorsrc
docs/playlist/dj-indo.md

Halo kak, izin berkontribusi. Saya baru update untuk playlist DJ indo. Terima kasih

add: DJ Indo playlist

---

docs/playlist/pop.md

Halo, saya telah menambahkan playlist lagu pop Indonesia di era tahun 2000-an pada file `pop.md`
Terima kasih

add "Pop Indonesia Hits 2000an" playlist to pop.md

---

docs/playlist/kpop.md

Added three playlists for k-pop
- TWICE
- Stray Kids
- ITZY

Added TWICE, SKZ, ITZY

---

.all-contributorsrc
docs/playlist/soul.md

I have added a new playlist in soul.md

Added A Special One

---

docs/playlist/dangdut.md

I have added vita alvia to dangdut.md, thanks

add vita alvia to dangdut playlist

---

docs/playlist/jpop.md
docs/playlist/pop.md

Last one for today, thank you for making this repo Satya  😁

add owl city and twice

---

docs/.vitepress/config.js
docs/playlist/soundtrack.md

I added another genre called Soundtrack with a few playlists

Added genre soundtrack with soundtrack.md file

---

docs/.vitepress/config.js
docs/playlist/indie.md

feat(genre): add playlist indie

---

docs/playlist/jpop.md

menambahkan lagu Hoshou Marine

---

docs/playlist/kpop.md

Tally Added

---

docs/playlist/pop.md

Thanks satya sudah mengajari kami git & github 🙌🙌

adding new playlist into pop playlist

---

docs/playlist/lofi-hiphop.md

Added a new lofi song to lofi-hiphop playlist

Added a new lofi song to lofi_hiphop playlist 
